# This is an example Ticket Bot's config file.

# Auto buy tickets on schedule time
[schedules]

[schedules.THSRC]
datetime = '' # datetime 預計訂票日期 (e.g. 2023-01-01 00:00)

# Copy user-agent from login browser (https://www.whatsmyua.info/)
[headers]
User-Agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

[directories]

[fields]

[fields.THSRC]
id = ''             # ROC ID No. 身分證字號 (e.g. AXXXXXXXXX)
start-station = ''  # Start-station 出發站 (e.g. Taipei)
dest-station = ''   # Dest-station 抵達站 (e.g. Tainan)
outbound-date = ''  # Outbound date 出發日期 (e.g. 2023-01-01)
outbound-time = ''  # Outbound time 出發時間 (e.g. 09:00)
inbound-time = ''   # Inbound time 抵達時間 (e.g. 12:00)
preferred-seat = '' # Preferred seat 座位偏好 (e.g. window/aisle)
car-type = ''       # Car Type 車廂類型 (e.g. normal/business)
train-no = ''       # Train No. 車次 (e.g. 001)
email = ''          # E-mail for notification
phone = ''          # Phone number for SMS notification 手機號碼
tgo-id = ''         # TSHRC member ID TGO會員ID (e.g. AXXXXXXXXX)

[fields.THSRC.ticket]
adult = 1    # 全票
child = 0    # 孩童票 (6-11)
disabled = 0 # 愛心票
elder = 0    # 敬老票
college = 0  # 大學生票

[proxies]
# This is a dictionary of proxies you wish to use on services that require a specific country IP.
# The dictionary key needs to be an alpha 2 country code (2-letter code, e.g. `us`, `gb`, `jp`, `de`).
# The value needs to be the proxy string which should be recognizable by python-requests and curl.
# e.g.: https://username:password123@subdomain.hostname.ext:89
# If you don't want any, just have this section blank or remove the [proxies] entirely
# us = 'http://127.0.0.1:7890' # Clash

[nordvpn]
# Like `proxies` above, this does the same thing except it automatically generates a proxy string
# for a nordvpn server automatically.
# The credentials should be `Service credentials` NOT your Nord account details!
# https://my.nordaccount.com/dashboard/nordvpn/ (Under advanced configuration).
# e.g.: https://support.nordvpn.com/Connectivity/Proxy/1087802472/Proxy-setup-on-qBittorrent.htm
username = ''
password = ''
