# This is an example Ticket Bot's config file.

# Auto buy tickets on schedule time
[schedules]

[schedules.THSRC]
datetime = '' # datetime (e.g. 2023-01-01 00:00)

# Copy user-agent from login browser (https://www.whatsmyua.info/)
[headers]
User-Agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

[directories]

[fields]

[fields.THSRC]
id = ''             # ROC ID No. (e.g. AXXXXXXXXX)
start-station = ''  # Start-station (e.g. Taipei)
dest-station = ''   # Dest-station (e.g. Tainan)
outbound-date = ''  # Outbound date (e.g. 2023-01-01)
outbound-time = ''  # Outbound time (e.g. 09:00)
inbound-time = ''   # Inbound time (e.g. 12:00)
preferred-seat = '' # Preferred seat e.g. window/aisle
train-class = ''    # Train class (e.g. normal/business)
train-no = ''       # Train No. (e.g. 001)
email = ''          # E-mail for notification
phone = ''          # Phone number for SMS notification
tgo-id = ''         # TSHRC member ID (e.g. AXXXXXXXXX)

[fields.THSRC.ticket]
adult = 1
elder = 0
child = 0
disabled = 0
college = 0

[proxies]
# This is a dictionary of proxies you wish to use on services that require a specific country IP.
# The dictionary key needs to be an alpha 2 country code (2-letter code, e.g. `us`, `gb`, `jp`, `de`).
# The value needs to be the proxy string which should be recognizable by python-requests and curl.
# e.g.: https://username:password123@subdomain.hostname.ext:89
# If you don't want any, just have this section blank or remove the [proxies] entirely
# us = 'http://127.0.0.1:7890' # Clash

[nordvpn]
# Like `proxies` above, this does the same thing except it automatically generates a proxy string
# for a nordvpn server automatically.
# The credentials should be `Service credentials` NOT your Nord account details!
# https://my.nordaccount.com/dashboard/nordvpn/ (Under advanced configuration).
# e.g.: https://support.nordvpn.com/Connectivity/Proxy/1087802472/Proxy-setup-on-qBittorrent.htm
username = ''
password = ''
